[package]
name = "parrhesia"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# Internal
poem-proxy = { path = "poem-proxy" }

# External
poem = { version = "1.3.48", features = [ "static-files" ] }
tokio = { version = "1.21.2", features = ["full"] }
dirs = "4.0.0"
surrealdb = "1.0.0-beta.8"
patch = "0.6.0"
