[package]
name = "budgeteer"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# Internal
migration = { path = "migration" }

# External
async-graphql = "4.0.16"
async-graphql-poem = "4.0.16"
poem = { version = "1.3.48", features = [ "static-files" ] }
rust-argon2 = "1.0.0"
sea-orm = { version = "0.10.1", features = ["sqlx-sqlite", "runtime-tokio-native-tls", "macros"] }
tokio = { version = "1.21.2", features = ["full"] }
dirs = "4.0.0"
jwt-simple = "0.11.2"
serde = "1.0.147"
